version = 1

[include]
environments = [
    { remote = "flox/postgres" }
]

[install]
requests.pkg-path = "python313Packages.requests"
sqlite.pkg-path = "sqlite"
psycopg2.pkg-path = "python313Packages.psycopg2"
termgraph.pkg-path = "python313Packages.termgraph"

[hook]
on-activate = '''

if [ -f .token ]; then
    export GITHUB_TOKEN=$(cat .token)
else
    echo "No .token file found. Please create one with your GitHub token."
fi
'''
